apiVersion: v1
kind: Template
metadata:
  name: grafana-operator
  annotations:
    openshift.io/display-name: "Grafana Datasource"
    description: >-
      Installs a datasource to call to central thanos querier in openshift missions
    tags: "monitoring"
    iconClass: "fa fa-exchange"
message: "Data source being created ${PROJECT_NAME}"
parameters:
- description: The name of the project the operator will be installed to
  displayName: Name of project
  name: PROJECT_NAME
  value: debezium-monitoring
  required: true
- description: The Token (for the sa with cluster-metrics-view privilege) that should be publish on the data source
  displayName: (Bearer) Token
  name: TOKEN
  required: true
objects:
- apiVersion: integreatly.org/v1alpha1
  kind: GrafanaDataSource
  metadata:
    name: example-grafanadatasource
    namespace: ${PROJECT_NAME}
  spec:
    datasources:
      - access: proxy
        name: Prometheus
        type: prometheus
        url: 'https://thanos-querier.openshift-monitoring.svc.cluster.local:9091'
        basicAuth: false
        withCredentials: false
        isDefault: false
        jsonData:
          timeInterval: 5s
          tlsSkipVerify: true
          httpHeaderName1: "Authorization"
        secureJsonData:
          httpHeaderValue1: "Bearer ${TOKEN}"
        editable: true
    name: example-datasources.yaml
