# see also documentation in the Fuse Online Operator page in the openshift cluster
apiVersion: syndesis.io/v1alpha1
kind: Syndesis
metadata:
  name: app
  namespace: debezium-cdc
spec:
  addons:
    todo:
      enabled: false
    ops:
      enabled: true
  components:
    db:
      resources: {}
    grafana:
      resources: {}
    komodo:
      resources: {}
    meta:
      resources: {}
    oauth: {}
    prometheus:
      resources: {}
    psql: {}
    s2i: {}
    server:
      features: {}
      resources: {}
    ui: {}
    upgrade:
      resources: {}
  integration:
    limit: 0