# NOTE: Find package names of operators by using this command
#  oc get packagemanifests -n openshift-marketplace
apiVersion: operators.coreos.com/v1
kind: CatalogSourceConfig
metadata:
  name: redhat-operators-packages
  namespace: openshift-marketplace
spec:
  targetNamespace: openshift-operators
  packages: amq-streams
  source: redhat-operators